/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ILoanManager } from "./ILoanManager";
export type { IOracle } from "./IOracle";
export type { IStaking } from "./IStaking";
export type { IVault } from "./IVault";
