name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
        with:
          version: 9
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
      - run: pnpm i -g hardhat
      - run: pnpm i --frozen-lockfile=false
      - name: Compile contracts
        run: |
          cd packages/contracts
          pnpm i --frozen-lockfile=false
          npx hardhat compile
      - name: Typecheck API
        run: |
          cd services/api
          pnpm i --frozen-lockfile=false
          pnpm build
      - name: Typecheck Keeper
        run: |
          cd services/keeper
          pnpm i --frozen-lockfile=false
          pnpm build


